Repository projen/projen, pull requests merged in 2021-11, with the labels that each got.

#1191 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1193 chore: use fake projen version in tests
  src/common.ts
  test/awscdk/__snapshots__/java-app.test.ts.snap
Labels: contribution/core

#1070 feat(awscdk): pre-bundled aws lambda functions
  .projen/deps.json
  .projen/tasks.json
  .projenrc.js
  API.md
  docs/aws-lambda.md
  package.json
  src/awscdk-app-ts.ts
  src/awscdk-construct.ts
  src/awscdk/auto-discover.ts
  src/awscdk/index.ts
  src/awscdk/internal.ts
  src/awscdk/lambda-function.ts
  src/eslint.ts
  src/github/workflows.ts
  src/index.ts
  src/inventory.ts
  src/javascript/bundler.ts
  src/javascript/index.ts
  src/node-project.ts
  src/python/projenrc.ts
  src/util.ts
  test/__snapshots__/inventory.test.ts.snap
  test/awscdk-app.test.ts
  test/awscdk-construct.test.ts
  test/awscdk/__snapshots__/lambda-function.test.ts.snap
  test/awscdk/lambda-function.test.ts
  test/javascript/bundler.test.ts
  yarn.lock
Labels: contribution/core

#1197 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1198 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1199 feat: sort tasks by name
  .projen/tasks.json
  package.json
  src/node-package.ts
  src/tasks/tasks.ts
Labels: contribution/core

#1203 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1207 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1206 fix: cannot configure mergify options
  API.md
  src/github/github.ts
  src/node-project.ts
  src/project.ts
  test/__snapshots__/inventory.test.ts.snap
Labels: contribution/core

#1209 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1212 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1213 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1214 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1216 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1218 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1221 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1223 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1225 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1226 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1224 feat: enforce conventional commits with PR linter
  .gitattributes
  .github/workflows/pull-request-lint.yml
  .gitignore
  API.md
  src/github/github.ts
  src/github/index.ts
  src/github/pull-request-lint.ts
  test/__snapshots__/integ.test.ts.snap
  test/__snapshots__/typescript.test.ts.snap
  test/awscdk/java-app.test.ts
  test/github/__snapshots__/pull-request-lint.test.ts.snap
  test/github/pull-request-lint.test.ts
  test/java/__snapshots__/java-project.test.ts.snap
  test/java/__snapshots__/projenrc.test.ts.snap
  test/json/__snapshots__/projenrc.test.ts.snap
  test/pr-template.test.ts
  test/python/__snapshots__/poetry.test.ts.snap
  test/python/__snapshots__/projenrc.test.ts.snap
  test/python/__snapshots__/python-project.test.ts.snap
  test/release/__snapshots__/release.test.ts.snap
  test/web/__snapshots__/nextjs-project.test.ts.snap
  test/web/__snapshots__/nextjs-ts-project.test.ts.snap
  test/web/__snapshots__/react-project.test.ts.snap
  test/web/__snapshots__/react-ts-project.test.ts.snap
Labels: contribution/core

#1200 fix(node): bundled assets cannot be located during tests
  API.md
  docs/aws-lambda.md
  docs/bundling.md
  src/awscdk-app-ts.ts
  src/awscdk-construct.ts
  src/awscdk/auto-discover.ts
  src/awscdk/lambda-function.ts
  src/javascript/bundler.ts
  src/javascript/util.ts
  src/node-project.ts
  src/project.ts
  test/__snapshots__/inventory.test.ts.snap
  test/awscdk-app.test.ts
  test/awscdk-construct.test.ts
  test/awscdk/__snapshots__/lambda-function.test.ts.snap
  test/awscdk/lambda-function.test.ts
  test/javascript/bundler.test.ts
Labels: contribution/core, pr/do-not-merge

#1229 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1231 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1232 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1236 chore: Revert "fix: lambdas are now produced with posix paths only"
  src/awscdk/lambda-function.ts
Labels: contribution/core

#1238 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1241 chore: add NPM keywords for projen
  .projenrc.js
  package.json
Labels: contribution/core

#1242 fix: README logo url
  README.md
Labels: contribution/core

#1243 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1245 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1248 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1251 chore: rfc - external repository settings
  rfcs/github-project-settings.md
Labels: contribution/core

#1252 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1253 chore: fix addBundle docstring
  API.md
  src/javascript/bundler.ts
Labels: contribution/core

#1254 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1257 feat: document AWS cloud development features
  VISION.md
  docs/aws-lambda.md
  docs/awscdk-apps.md
  docs/awscdk-construct.md
  docs/awscdk.md
Labels: contribution/core

#1258 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1255 fix: release.yml cannot be modified with escape hatches
  .gitignore
  API.md
  src/github/github.ts
  src/github/workflows.ts
  src/release/publisher.ts
  src/release/release.ts
  src/upgrade-dependencies.ts
  test/__snapshots__/integ.test.ts.snap
  test/__snapshots__/typescript.test.ts.snap
  test/github/workflows.test.ts
  test/release/__snapshots__/release.test.ts.snap
  test/release/release.test.ts
  test/web/__snapshots__/nextjs-project.test.ts.snap
  test/web/__snapshots__/react-project.test.ts.snap
Labels: contribution/core

#1260 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1261 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1262 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1263 chore: improve error output for projen synth
  src/cli/synth.ts
Labels: contribution/core

#1271 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1270 feat(awscdk): integration tests
  API.md
  docs/awscdk.md
  src/awscdk-app-ts.ts
  src/awscdk-construct.ts
  src/awscdk/auto-discover.ts
  src/awscdk/cdk-config.ts
  src/awscdk/index.ts
  src/awscdk/integration-test.ts
  src/awscdk/internal.ts
  test/__snapshots__/inventory.test.ts.snap
  test/awscdk/__snapshots__/integration-test.test.ts.snap
  test/awscdk/integration-test.test.ts
  test/awscdk/lambda-function.test.ts
Labels: contribution/core
