Repository projen/projen, pull requests merged in 2021-12, with the labels that each got.

#1274 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1275 fix: snapshot resolver not cleaned up
  .projen/jest-snapshot-resolver.js
  src/typescript.ts
Labels: contribution/core

#1279 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1278 fix: jsdom typings override is no longer needed
  .projenrc.js
  package.json
  yarn.lock
Labels: contribution/core

#1280 fix: ansi-regex has a security volunerability (CVE-2021-3807)
  .projen/deps.json
  package.json
  src/jest.ts
  test/__snapshots__/integ.test.ts.snap
  yarn.lock
Labels: contribution/core

#1281 fix: eslint depends on insecure library (ansi-regex)
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/upgrade-main.yml
  .projen/deps.json
  .projen/tasks.json
  .projenrc.js
  package.json
  src/awscdk-construct.ts
  src/eslint.ts
  src/jest.ts
  src/tasks/task.ts
  test/__snapshots__/integ.test.ts.snap
  yarn.lock
Labels: contribution/core

#1283 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1285 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1290 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1291 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1298 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1300 fix(awscdk-construct): integration tests cannot be executed
  API.md
  src/awscdk/auto-discover.ts
  src/awscdk/awscdk-app-ts.ts
  src/awscdk/awscdk-construct.ts
  src/awscdk/integration-test.ts
  test/awscdk/__snapshots__/integration-test.test.ts.snap
  test/awscdk/integration-test.test.ts
  test/awscdk/lambda-function.test.ts
Labels: contribution/core

#1302 fix(awscdk): integ tests are still not working for libraries
  API.md
  src/awscdk/integration-test.ts
  src/dependencies.ts
  test/awscdk/__snapshots__/integration-test.test.ts.snap
  test/awscdk/integration-test.test.ts
  test/deps.test.ts
Labels: contribution/core

#1308 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1303 fix: remove gitattributes spacing alignment
  .gitattributes
  src/gitattributes.ts
  test/__snapshots__/integ.test.ts.snap
  test/java/__snapshots__/java-project.test.ts.snap
  test/java/__snapshots__/projenrc.test.ts.snap
  test/json/__snapshots__/projenrc.test.ts.snap
  test/python/__snapshots__/poetry.test.ts.snap
  test/python/__snapshots__/projenrc.test.ts.snap
  test/python/__snapshots__/python-project.test.ts.snap
  test/release/__snapshots__/release.test.ts.snap
  test/web/__snapshots__/nextjs-project.test.ts.snap
  test/web/__snapshots__/nextjs-ts-project.test.ts.snap
  test/web/__snapshots__/react-project.test.ts.snap
  test/web/__snapshots__/react-ts-project.test.ts.snap
Labels: contribution/core

#1305 chore: update contributors list
  .all-contributorsrc
  README.md
Labels: contribution/core

#1311 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1314 feat(release): allow specifying npm dist-tag per branch
  .projen/tasks.json
  API.md
  package.json
  src/cdk/jsii-project.ts
  src/github/workflows.ts
  src/javascript/node-package.ts
  src/javascript/node-project.ts
  src/release/publisher.ts
  src/release/release.ts
  test/__snapshots__/integ.test.ts.snap
  test/__snapshots__/inventory.test.ts.snap
  test/jsii.test.ts
  test/node-project.test.ts
  test/release/__snapshots__/release.test.ts.snap
  test/release/release.test.ts
  test/web/__snapshots__/nextjs-project.test.ts.snap
  test/web/__snapshots__/react-project.test.ts.snap
Labels: contribution/core

#1316 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1321 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1322 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1325 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1323 feat(awscdk-app-ts): support cdk watch
  API.md
  docs/awscdk.md
  src/awscdk/awscdk-app-ts.ts
  src/awscdk/cdk-config.ts
  src/awscdk/cdk-tasks.ts
  src/javascript/bundler.ts
  src/task.ts
  test/__snapshots__/inventory.test.ts.snap
  test/awscdk-app.test.ts
  test/tasks/tasks.test.ts
Labels: contribution/core

#1327 fix(awscdk): some issues with CDK v2
  API.md
  src/awscdk/auto-discover.ts
  src/awscdk/awscdk-app-ts.ts
  src/awscdk/awscdk-construct.ts
  src/awscdk/awscdk-deps.ts
  src/awscdk/index.ts
  src/awscdk/lambda-function.ts
  test/__snapshots__/integ.test.ts.snap
  test/__snapshots__/inventory.test.ts.snap
  test/__snapshots__/new.test.ts.snap
  test/awscdk/__snapshots__/lambda-function.test.ts.snap
  test/awscdk/awscdk-app.test.ts
  test/awscdk/awscdk-construct.test.ts
  test/awscdk/lambda-function.test.ts
  test/integration/cdk-watchful.projenrc.js
Labels: contribution/core, pr/do-not-merge

#1337 chore: Revert "fix(awscdk): some issues with CDK v2 (#1327)"
  API.md
  src/awscdk/auto-discover.ts
  src/awscdk/awscdk-app-ts.ts
  src/awscdk/awscdk-construct.ts
  src/awscdk/awscdk-deps.ts
  src/awscdk/index.ts
  src/awscdk/lambda-function.ts
  test/__snapshots__/integ.test.ts.snap
  test/__snapshots__/inventory.test.ts.snap
  test/__snapshots__/new.test.ts.snap
  test/awscdk-app.test.ts
  test/awscdk-construct.test.ts
  test/awscdk/__snapshots__/lambda-function.test.ts.snap
  test/awscdk/lambda-function.test.ts
  test/integration/cdk-watchful.projenrc.js
Labels: contribution/core

#1338 fix(awscdk): issues with CDK v2 libraries and apps (take 2)
  API.md
  src/awscdk/auto-discover.ts
  src/awscdk/awscdk-app-ts.ts
  src/awscdk/awscdk-construct.ts
  src/awscdk/awscdk-deps.ts
  src/awscdk/index.ts
  src/awscdk/lambda-function.ts
  src/javascript/node-package.ts
  test/__snapshots__/integ.test.ts.snap
  test/__snapshots__/inventory.test.ts.snap
  test/__snapshots__/new.test.ts.snap
  test/awscdk/__snapshots__/lambda-function.test.ts.snap
  test/awscdk/awscdk-app.test.ts
  test/awscdk/awscdk-construct.test.ts
  test/awscdk/lambda-function.test.ts
  test/node-project.test.ts
Labels: contribution/core, pr/do-not-merge

#1346 feat: init python projects with .projenrc.py
  API.md
  src/python/projenrc.ts
  src/python/python-project.ts
  test/__snapshots__/inventory.test.ts.snap
  test/__snapshots__/new.test.ts.snap
  test/python/__snapshots__/poetry.test.ts.snap
  test/python/__snapshots__/projenrc.test.ts.snap
  test/python/__snapshots__/python-project.test.ts.snap
Labels: contribution/core

#1350 feat: projen library in go
  .github/workflows/integ.yml
  .github/workflows/release.yml
  .projenrc.js
  API.md
  package.json
  src/cli/cmds/new.ts
  src/java/projenrc.ts
  src/javascript/projenrc.ts
  src/javascript/render-options.ts
  src/option-hints.ts
  src/project.ts
  src/projects.ts
  src/projenrc-json.ts
  src/python/projenrc.ts
  src/run-projenrc-json.task.ts
  src/typescript/projenrc.ts
  test/java/java-project.test.ts
  test/java/projenrc.test.ts
  test/json/projenrc.test.ts
  test/projects.test.ts
  test/python/projenrc.test.ts
Labels: contribution/core

#1352 feat(release): improve performance
  .github/workflows/release.yml
  src/release/publisher.ts
  test/__snapshots__/integ.test.ts.snap
  test/__snapshots__/jsii.test.ts.snap
  test/release/__snapshots__/release.test.ts.snap
  test/release/release.test.ts
  test/web/__snapshots__/nextjs-project.test.ts.snap
  test/web/__snapshots__/react-project.test.ts.snap
Labels: contribution/core

#1354 chore: fix Python version in release workflow
  .github/workflows/release.yml
  src/release/publisher.ts
  test/__snapshots__/integ.test.ts.snap
  test/release/__snapshots__/release.test.ts.snap
Labels: contribution/core

#1351 feat: allow overriding deps
  docs/deps.md
  src/dependencies.ts
  test/deps.test.ts
  test/typescript/__snapshots__/typescript.test.ts.snap
  test/typescript/typescript.test.ts
  test/web/react-ts-project.test.ts
Labels: contribution/core

#1359 feat(jsii): parallelize build of language bindings
  .github/workflows/build.yml
  .github/workflows/integ.yml
  .github/workflows/release.yml
  .github/workflows/upgrade-main.yml
  .projen/deps.json
  .projen/tasks.json
  .projenrc.js
  API.md
  docs/build.md
  docs/mutable-builds.md
  docs/project.md
  docs/publisher.md
  package.json
  src/build/build-workflow.ts
  src/build/index.ts
  src/cdk/consts.ts
  src/cdk/jsii-project.ts
  src/github/constants.ts
  src/github/github.ts
  src/github/task-workflow.ts
  src/github/workflows-model.ts
  src/github/workflows.ts
  src/index.ts
  src/javascript/node-project.ts
  src/javascript/upgrade-dependencies.ts
  src/release/publisher.ts
  src/release/release.ts
  src/typescript/typescript.ts
  test/__snapshots__/integ.test.ts.snap
  test/__snapshots__/inventory.test.ts.snap
  test/__snapshots__/jsii.test.ts.snap
  test/__snapshots__/node-project.test.ts.snap
  test/__snapshots__/upgrade-dependencies.test.ts.snap
  test/awscdk/awscdk-construct.test.ts
  test/cdk/__snapshots__/jsii.test.ts.snap
  test/cdk/jsii.test.ts
  test/github/__snapshots__/task-workflow.test.ts.snap
  test/node-project.test.ts
  test/release/__snapshots__/release.test.ts.snap
  test/release/release.test.ts
  test/upgrade-dependencies.test.ts
  test/web/__snapshots__/nextjs-project.test.ts.snap
  test/web/__snapshots__/nextjs-ts-project.test.ts.snap
  test/web/__snapshots__/react-project.test.ts.snap
  test/web/__snapshots__/react-ts-project.test.ts.snap
  yarn.lock
Labels: contribution/core

#1363 feat(release): dry-run
  .mergify.yml
  .projen/tasks.json
  .projenrc.js
  docs/publisher.md
  test/release/release.test.ts
Labels: contribution/core

#1336 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1374 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1366 chore: enable publishing
  .github/workflows/release.yml
  .projenrc.js
Labels: contribution/core

#1377 fix(node): npm releases are broken for non-jsii projects
  .github/workflows/build.yml
  .github/workflows/release.yml
  .projen/tasks.json
  API.md
  src/cdk/jsii-project.ts
  src/javascript/node-project.ts
  test/__snapshots__/integ.test.ts.snap
  test/cdk/__snapshots__/jsii.test.ts.snap
  test/web/__snapshots__/nextjs-project.test.ts.snap
  test/web/__snapshots__/react-project.test.ts.snap
Labels: contribution/core

#1379 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1401 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1411 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1383 fix(workflows): status check update is not working
  .github/workflows/build.yml
  .github/workflows/integ.yml
  .github/workflows/release.yml
  .github/workflows/upgrade-main.yml
  .projenrc.js
  API.md
  src/build/build-workflow.ts
  src/cli/cmds/new.ts
  src/github/auto-approve.ts
  src/github/constants.ts
  src/github/github-project.ts
  src/github/github.ts
  src/github/task-workflow.ts
  src/github/workflow-actions.ts
  src/github/workflows.ts
  src/javascript/jest.ts
  src/javascript/node-project.ts
  src/javascript/upgrade-dependencies.ts
  src/release/release.ts
  test/__snapshots__/integ.test.ts.snap
  test/__snapshots__/inventory.test.ts.snap
  test/__snapshots__/new.test.ts.snap
  test/__snapshots__/node-project.test.ts.snap
  test/__snapshots__/projects.test.ts.snap
  test/__snapshots__/upgrade-dependencies.test.ts.snap
  test/cdk/__snapshots__/jsii.test.ts.snap
  test/cdk/jsii.test.ts
  test/github/__snapshots__/auto-approve.test.ts.snap
  test/github/__snapshots__/task-workflow.test.ts.snap
  test/github/auto-approve.test.ts
  test/node-project.test.ts
  test/release/__snapshots__/release.test.ts.snap
  test/release/bump.test.ts
  test/upgrade-dependencies.test.ts
  test/util.ts
  test/web/__snapshots__/nextjs-project.test.ts.snap
  test/web/__snapshots__/nextjs-ts-project.test.ts.snap
  test/web/__snapshots__/react-project.test.ts.snap
  test/web/__snapshots__/react-ts-project.test.ts.snap
Labels: contribution/core, pr/do-not-merge

#1414 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1416 fix(jsii): upgrade workflow no longer needs to run pacmak
  .github/workflows/build.yml
  .github/workflows/upgrade-main.yml
  .projen/tasks.json
  src/build/build-workflow.ts
  src/cdk/consts.ts
  src/cdk/jsii-project.ts
  src/github/workflow-actions.ts
  src/release/release.ts
Labels: contribution/core

#1406 fix(mergify): not all build jobs are considered
  .mergify.yml
  API.md
  src/github/auto-merge.ts
  src/javascript/node-project.ts
  test/__snapshots__/integ.test.ts.snap
Labels: contribution/core

#1417 fix(workflows): mutation check did not consider unstaged changes
  .github/workflows/build.yml
  .github/workflows/upgrade-main.yml
  .projen/tasks.json
  src/build/build-workflow.ts
  src/github/workflow-actions.ts
  src/javascript/upgrade-dependencies.ts
  src/release/release.ts
  test/__snapshots__/integ.test.ts.snap
  test/__snapshots__/node-project.test.ts.snap
  test/__snapshots__/upgrade-dependencies.test.ts.snap
  test/web/__snapshots__/nextjs-project.test.ts.snap
  test/web/__snapshots__/nextjs-ts-project.test.ts.snap
  test/web/__snapshots__/react-project.test.ts.snap
  test/web/__snapshots__/react-ts-project.test.ts.snap
Labels: contribution/core

#1425 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1428 fix(build): build should fail if mutations were found
  .github/workflows/build.yml
  src/build/build-workflow.ts
  src/github/workflow-actions.ts
  test/__snapshots__/integ.test.ts.snap
  test/__snapshots__/node-project.test.ts.snap
  test/cdk/__snapshots__/jsii.test.ts.snap
  test/web/__snapshots__/nextjs-project.test.ts.snap
  test/web/__snapshots__/nextjs-ts-project.test.ts.snap
  test/web/__snapshots__/react-project.test.ts.snap
  test/web/__snapshots__/react-ts-project.test.ts.snap
Labels: contribution/core

#1429 fix(build): anti-tamper job is redundant
  .github/workflows/build.yml
  .github/workflows/upgrade-main.yml
  src/build/build-workflow.ts
  src/github/workflow-actions.ts
  test/__snapshots__/integ.test.ts.snap
  test/__snapshots__/node-project.test.ts.snap
  test/__snapshots__/upgrade-dependencies.test.ts.snap
  test/cdk/jsii.test.ts
  test/node-project.test.ts
  test/web/__snapshots__/nextjs-project.test.ts.snap
  test/web/__snapshots__/nextjs-ts-project.test.ts.snap
  test/web/__snapshots__/react-project.test.ts.snap
  test/web/__snapshots__/react-ts-project.test.ts.snap
Labels: contribution/core

#1430 chore: improve mutation error message
  .github/workflows/build.yml
  src/build/build-workflow.ts
  src/github/workflow-actions.ts
  test/__snapshots__/integ.test.ts.snap
  test/__snapshots__/node-project.test.ts.snap
  test/web/__snapshots__/nextjs-project.test.ts.snap
  test/web/__snapshots__/nextjs-ts-project.test.ts.snap
  test/web/__snapshots__/react-project.test.ts.snap
  test/web/__snapshots__/react-ts-project.test.ts.snap
Labels: contribution/core

#1435 feat(node): do run "yarn/npm install" if package.json did not change
  API.md
  src/file.ts
  src/javascript/node-package.ts
  src/json.ts
  src/util.ts
  test/__snapshots__/integ.test.ts.snap
  test/json.test.ts
  test/node-project.test.ts
  test/web/__snapshots__/nextjs-project.test.ts.snap
  test/web/__snapshots__/nextjs-ts-project.test.ts.snap
  test/web/__snapshots__/react-project.test.ts.snap
  test/web/__snapshots__/react-ts-project.test.ts.snap
  test/web/react-ts-project.test.ts
Labels: contribution/core

#1438 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve
