Repository projen/projen, pull requests merged in 2022-01, with the labels that each got.

#1445 chore(deps): upgrade dependencies
  package.json
  test/__snapshots__/license.test.ts.snap
  yarn.lock
Labels: auto-approve

#1448 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1450 feat(eslint): use prettier if enabled
  API.md
  docs/components.md
  src/javascript/eslint.ts
  src/javascript/node-project.ts
  src/javascript/prettier.ts
  test/__snapshots__/inventory.test.ts.snap
  test/eslint.test.ts
  test/prettier.test.ts
  test/project.test.ts
Labels: contribution/core

#1451 fix(node): lockfile not updated after "*" deps are resolved
  src/javascript/node-package.ts
  test/javascript/node-package.test.ts
  test/util.ts
Labels: contribution/core

#1456 fix(jest): tests are picked up from `dist/`
  API.md
  package.json
  src/javascript/jest.ts
  src/typescript/typescript.ts
  test/__snapshots__/integ.test.ts.snap
Labels: contribution/core

#1458 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1426 fix: package-js task not checked by mergify
  .gitattributes
  .github/workflows/build.yml
  .github/workflows/integ.yml
  .gitignore
  .mergify.yml
  .projen/files.json
  .projen/tasks.json
  .projenrc.js
  API.md
  src/build/build-workflow.ts
  test/gitlab/gitlab-configuration.test.ts
Labels: contribution/core

#1467 feat(build): allow lockfile mutations
  .github/workflows/build.yml
  API.md
  src/javascript/node-project.ts
  src/javascript/upgrade-dependencies.ts
  test/__snapshots__/integ.test.ts.snap
  test/__snapshots__/node-project.test.ts.snap
  test/web/__snapshots__/nextjs-project.test.ts.snap
  test/web/__snapshots__/nextjs-ts-project.test.ts.snap
  test/web/__snapshots__/react-project.test.ts.snap
  test/web/__snapshots__/react-ts-project.test.ts.snap
Labels: contribution/core

#1477 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1481 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1487 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1490 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1493 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1497 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1498 chore: update mutableBuild unit tests
  test/__snapshots__/node-project.test.ts.snap
  test/node-project.test.ts
Labels: contribution/core

#1499 chore: change author to AWS
  .projenrc.js
  package.json
Labels: contribution/core

#1501 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1510 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1509 fix(build-workflow): self mutation commits are not signed
  .github/workflows/build.yml
  src/build/build-workflow.ts
  test/__snapshots__/integ.test.ts.snap
  test/__snapshots__/node-project.test.ts.snap
  test/web/__snapshots__/nextjs-project.test.ts.snap
  test/web/__snapshots__/nextjs-ts-project.test.ts.snap
  test/web/__snapshots__/react-project.test.ts.snap
  test/web/__snapshots__/react-ts-project.test.ts.snap
Labels: contribution/core

#1516 chore: resynth after compiling projen
  .projen/tasks.json
  .projenrc.js
Labels: contribution/core

#1517 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1523 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1526 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1530 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1531 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1533 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1542 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1545 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1544 feat(stale): skip issues with "backlog" label
  .github/workflows/stale.yml
  API.md
  src/github/stale-util.ts
  src/github/stale.ts
  test/__snapshots__/integ.test.ts.snap
  test/github/__snapshots__/stale.test.ts.snap
  test/github/stale.test.ts
  test/java/__snapshots__/java-project.test.ts.snap
  test/java/__snapshots__/projenrc.test.ts.snap
  test/json/__snapshots__/projenrc.test.ts.snap
  test/python/__snapshots__/poetry.test.ts.snap
  test/python/__snapshots__/projenrc.test.ts.snap
  test/python/__snapshots__/python-project.test.ts.snap
  test/release/__snapshots__/release.test.ts.snap
  test/web/__snapshots__/nextjs-project.test.ts.snap
  test/web/__snapshots__/nextjs-ts-project.test.ts.snap
  test/web/__snapshots__/react-project.test.ts.snap
  test/web/__snapshots__/react-ts-project.test.ts.snap
Labels: contribution/core, pr/do-not-merge

#1546 chore: disable yaml folding
  .github/workflows/auto-approve.yml
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/stale.yml
  .github/workflows/upgrade-main.yml
  .projen/deps.json
  .projenrc.js
  API.md
  package.json
  src/yaml.ts
  test/__snapshots__/integ.test.ts.snap
  test/__snapshots__/upgrade-dependencies.test.ts.snap
  test/cdk/__snapshots__/jsii.test.ts.snap
  test/github/__snapshots__/auto-approve.test.ts.snap
  test/github/__snapshots__/stale.test.ts.snap
  test/java/__snapshots__/java-project.test.ts.snap
  test/java/__snapshots__/projenrc.test.ts.snap
  test/json/__snapshots__/projenrc.test.ts.snap
  test/python/__snapshots__/poetry.test.ts.snap
  test/python/__snapshots__/projenrc.test.ts.snap
  test/python/__snapshots__/python-project.test.ts.snap
  test/release/__snapshots__/release.test.ts.snap
  test/web/__snapshots__/nextjs-project.test.ts.snap
  test/web/__snapshots__/nextjs-ts-project.test.ts.snap
  test/web/__snapshots__/react-project.test.ts.snap
  test/web/__snapshots__/react-ts-project.test.ts.snap
  yarn.lock
Labels: contribution/core

#1549 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1550 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1552 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1555 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1561 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1565 chore(deps): upgrade dependencies
  package.json
  yarn.lock
Labels: auto-approve

#1566 chore: prepare projen docs for GitHub pages
  .gitignore
  .projen/tasks.json
  .projenrc.js
  docs/README.md
  docs/api/API.md
  docs/mutable-builds.md
  src/cdk/jsii-docgen.ts
  src/cdk/jsii-project.ts
  test/__snapshots__/integ.test.ts.snap
  test/__snapshots__/inventory.test.ts.snap
  test/cdk/jsii.test.ts
Labels: contribution/core

#1567 chore: update README links to point to docs site
  README.md
  src/inventory.ts
  test/__snapshots__/inventory.test.ts.snap
Labels: contribution/core

#1569 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1572 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1574 chore: add CNAME file
  docs/CNAME
Labels: contribution/core

#1576 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve

#1580 chore(deps): upgrade dependencies
  yarn.lock
Labels: auto-approve
